NationalGenomicsInfrastructure/ngi_pipeline

ngi_pipeline/database/filesystem.py

I know this is too many pull requests but at least I'm merging them myself

Make bad code that I wrote better

---

ngi_pipeline/conductor/flowcell.py
ngi_pipeline/conductor/launchers.py
ngi_pipeline/engines/piper_ngi/local_process_tracking.py

@vezzi, I'd like to go through the code once and discuss where we should send notifications to the operators. I've marked places in the code where I think we should do this but I think it would be easiest if we went through these together so we can discuss the flow.

Specify places in the code flow where operators must be notified

---

ngi_pipeline/engines/piper_ngi/launchers.py
ngi_pipeline/engines/piper_ngi/workflows.py

Also change the default time to match between the two files.

Change queue from node to core to use 8 cores instead of 16

---

milou_ngi_config.yaml
nestor_ngi_config.yaml

Update config file to use 8 threads when running Piper

---

ngi_pipeline/utils/communication.py
ngi_pipeline/utils/test_communication.py

also I fixed the test. I'll stop drinking coffee now.

Alright I got a little OCD about the formatting

---

ngi_pipeline/engines/piper_ngi/launchers.py
ngi_pipeline/engines/piper_ngi/local_process_tracking.py
ngi_pipeline/utils/filesystem.py
ngi_pipeline/utils/test_filesystem.py
scripts/create_charon_project_from_filesystem.py

Work in progress
Will resolve https://trello.com/c/3OrV0J6Z/84-userland-helper-scripts-for-ngi-pipeline

wrote tests. last time ever.

---

ngi_pipeline/conductor/flowcell.py
ngi_pipeline/conductor/launchers.py
ngi_pipeline/engines/piper_ngi/command_creation.py
ngi_pipeline/engines/piper_ngi/launchers.py
scripts/ngi_pipeline_start.py
scripts/start_pipeline_from_project.py

And also the rotation of the old analysis

Restart failed/finished jobs, clean up sbatch file

---

ngi_pipeline/engines/piper_ngi/local_process_tracking.py

I don't expect this to come up a lot but now I've changed the code so that the inability to parse a qc metrics file will not be like a fatal error. So the record of the job in the local database will be deleted (so long as Charon can be updated with the new sample and seqrun status values). The advantage of this is you won't get fifty mails an hour until you fix it; the disadvantage is that if you want to parse the qc metrics files you'll have to do it yourself, if they do in fact exist.

I don't know man I guess this will work

---

ngi_pipeline/conductor/flowcell.py
ngi_pipeline/utils/communication.py
ngi_pipeline/utils/filesystem.py

Alright this will work with the format we have decided upon for XTen flowcells. I've tested it with `141229_ST-E00214_0019_AH00V3CCXX` but if there are any from Uppsala it would be nice to test with those as well.

Parse XTen Flowcells

---

ngi_pipeline/conductor/flowcell.py

sample folders are going to be named Sample_<samplename> again

---

ngi_pipeline/engines/piper_ngi/launchers.py
ngi_pipeline/utils/filesystem.py

Fix rotation

---

ngi_pipeline/engines/piper_ngi/launchers.py
ngi_pipeline/engines/piper_ngi/local_process_tracking.py
ngi_pipeline/engines/piper_ngi/utils.py

I'm repeating code here but I think it looks uglier the other way. I dunno. Someone can change it if they want to.

One giant bugfix

---

ngi_pipeline/engines/piper_ngi/launchers.py

This undoes a thing we did because I realized we should copy bag the log files that report why the error occured. I think it should be fine. Right? Right.

Copy back files even if job fails

---

scripts/process_organize_flowcell.py

but we do in fact want to symlink the files.

I'm unsure what my thinking was here

---

ngi_pipeline/conductor/flowcell.py

Parse internal Uppsala research project names as well

---

ngi_pipeline/utils/communication.py

not tested but what could go wrong?

Add project name to ngi_operators emails

---

ngi_pipeline/engines/piper_ngi/launchers.py

Also improves slightly the logging of when commands start during execution of the sbatch file.

Write piper return code -after- files have finished transferring

---

ngi_pipeline/conductor/flowcell.py
ngi_pipeline/utils/parsers.py
ngi_pipeline/utils/test_parsers.py

I tested this locally! Someone let me know if it breaks everything. It should work for all samplesheets and either flowcell format (CASAVA v1.8 or v2.5)

Parse new samplesheet format; change libprep assignment; generalize fc parsing

---

ngi_pipeline/conductor/launchers.py
ngi_pipeline/engines/piper_ngi/launchers.py
ngi_pipeline/engines/piper_ngi/local_process_tracking.py

delete previous analysis

---

ngi_pipeline/engines/piper_ngi/launchers.py
ngi_pipeline/engines/piper_ngi/local_process_tracking.py

my bad, though this was pushed with the previous one.

forgot some things

---

ngi_pipeline/conductor/flowcell.py
ngi_pipeline/conductor/launchers.py
ngi_pipeline/engines/piper_ngi/command_creation.py
ngi_pipeline/utils/classes.py
scripts/ngi_pipeline_start.py

should actually copy the results back

its on fire

---

ngi_pipeline/engines/piper_ngi/launchers.py
ngi_pipeline/engines/piper_ngi/local_process_tracking.py

adding rsync error code handling

---

ngi_pipeline/engines/piper_ngi/launchers.py

Some days you should just put the keyboard down and realize you're doing more harm than good

How many errors does it take to break the will of the operators

---

milou_ngi_config.yaml
nestor_ngi_config.yaml
ngi_pipeline/conductor/launchers.py
ngi_pipeline/engines/piper_ngi/launchers.py
ngi_pipeline/engines/qc_ngi/__init__.py
ngi_pipeline/engines/qc_ngi/launchers.py
ngi_pipeline/engines/qc_ngi/workflows.py
ngi_pipeline/utils/pyutils.py

and no, I didn't test all of it

Yeah that's right, I'm PRing at 1:17 AM

---

ngi_pipeline/conductor/launchers.py
ngi_pipeline/engines/piper_ngi/launchers.py
ngi_pipeline/engines/qc_ngi/launchers.py

Sisiphysean. Why don't I just leave them out from the beginning? A timeless riddle that speaks to the soul of what it is to be human, I suppose

Remove all the bugs I introduced last night

---

ngi_pipeline/engines/piper_ngi/command_creation.py
ngi_pipeline/engines/piper_ngi/local_process_tracking.py

Get information from places

---

ngi_pipeline/engines/piper_ngi/local_process_tracking.py

Sorry Senthil, another PR. I told you I'd try but I didn't promise!

Don't break things if we're running locally

---

ngi_pipeline/conductor/launchers.py
ngi_pipeline/database/filesystem.py
ngi_pipeline/engines/piper_ngi/local_process_tracking.py

Robusify somewhat

---

ngi_pipeline/conductor/flowcell.py
requirements.txt
scripts/ngi_pipeline_start.py

User verification for reruns / deleting previous analyses

---

ngi_pipeline/server/handlers.py

Update DOCSTRING to reflect current usage

---

nestor_ngi_config.yaml
ngi_pipeline/conductor/flowcell.py

Allow user to pass path to demux flowcell directories as names

---

ngi_pipeline/engines/piper_ngi/test_command_creation.py

added test for command creation

---

scripts/ngi_pipeline_start.py

Another easy one! Tack Guillem!

A PR by any other name smells as sweet

---

ngi_pipeline/conductor/flowcell.py
ngi_pipeline/utils/filesystem.py
ngi_pipeline/utils/test_filesystem.py

Functions to locate a flowcell or project using the config info if they're passed as just a name

---

ngi_pipeline/conductor/flowcell.py
ngi_pipeline/engines/piper_ngi/local_process_tracking.py
scripts/project_completion.py

User script to print the status values for a project and its samples & seqruns; open to suggestions from users as to improvements/ changes

WIP Project completion script

---

scripts/project_completion.py

my logic wasn't so smarty as I thought it was

I'm a dummy

---

nestor_ngi_config.yaml
ngi_pipeline/engines/piper_ngi/launchers.py
ngi_pipeline/engines/piper_ngi/workflows.py
scripts/ngi_pipeline_start.py

Super charge Piper

---

ngi_pipeline/conductor/flowcell.py
ngi_pipeline/conductor/launchers.py
ngi_pipeline/database/classes.py
ngi_pipeline/database/filesystem.py
ngi_pipeline/engines/piper_ngi/launchers.py
ngi_pipeline/engines/piper_ngi/local_process_tracking.py
ngi_pipeline/engines/piper_ngi/utils.py
ngi_pipeline/engines/piper_ngi/workflows.py
ngi_pipeline/utils/communication.py
ngi_pipeline/utils/test_communication.py
scripts/ngi_pipeline_start.py
scripts/print_running_jobs.py

This shouldn't be merged until Charon has the relevant fields, and once these are decided upon it will probably need a couple of small changes to the pieces that update Charon status fields.

WIP Genotype concordance analysis integration with Charon

---

nestor_ngi_config.yaml

set Shell as the behavior in the config file

---

nestor_ngi_config.yaml
ngi_pipeline/database/classes.py
ngi_pipeline/engines/piper_ngi/launchers.py
ngi_pipeline/engines/piper_ngi/local_process_tracking.py
ngi_pipeline/engines/piper_ngi/results_parsers.py
ngi_pipeline/engines/piper_ngi/utils.py
ngi_pipeline/utils/charon.py
ngi_pipeline/utils/parsers.py
scripts/ngi_pipeline_start.py

Now with bonus fields and values that are accurate, genotype concordance output file parsing, and automatic updating of Charon when the genotype jobs finish. I need to add a script cron can use to check for incoming genotyping files.

Genotype concordance analysis, again

---

ngi_pipeline/conductor/flowcell.py
ngi_pipeline/conductor/launchers.py
ngi_pipeline/engines/piper_ngi/launchers.py
ngi_pipeline/engines/piper_ngi/utils.py
ngi_pipeline/utils/filesystem.py
scripts/ngi_pipeline_start.py

Also a `--no-qc` flag to avoid launching qc analysis when launching normal analysis

add --keep-existing-files flag

---

ngi_pipeline/engines/piper_ngi/workflows.py

retry failed update

---

nestor_ngi_config.yaml
ngi_pipeline/conductor/flowcell.py
ngi_pipeline/utils/filesystem.py

the topdir will depend on the flowcell location now

top dir depends on flowcell root

---

nestor_ngi_config.yaml
ngi_pipeline/conductor/flowcell.py
ngi_pipeline/utils/filesystem.py
scripts/check_parse_genotype_files.py

adding multiple inboxes

---

ngi_pipeline/conductor/flowcell.py

too many brackets makes jack a dull boy

fixing regex

---

ngi_pipeline/engines/piper_ngi/launchers.py

also, partially solves the multiple fastq files copied

Fixing status being written to the wrong sample 

---

ngi_pipeline/conductor/flowcell.py

also update sthlm x regex

---

ngi_pipeline/engines/piper_ngi/launchers.py
ngi_pipeline/engines/piper_ngi/utils.py

Also, this fixes the pipeline trying to delete the same file more than once, and also logs every file deletion, in case I missed something.

fixing data deletion

---

ngi_pipeline/database/filesystem.py
scripts/ngi_pipeline_start.py

This should handle the case where the network lets us down on charon updates

adding retry and error handling in charon updates

---

nestor_ngi_config.yaml

update config file

---

scripts/applyRecalibration.sh
scripts/bam2fastq.sh

- This should fix issue with fastq files not being synced back from scratch 
- Upped the resources used

copy results back from node instead of move, upped resources

---

scripts/NGI_pipeline_test.py

First version of the script to create the test dataset.
It wants as input
- fastq file for read 1
- fastq file for read 2
- number of FC to create
- a bunch of other options
it creates in the current working dir the specified FCs, containing 8 samples each (1 per lane).
It populates charon accordingly.
It supports both Stockholm and Uppsala naming conventions.
TODO: I want to add the possibility to have pooled lanes (i.e. each sample is sequenced in 8 lanes in the same FC) but this can be done later.
@b97pla I choose you!!! (like the pokemon)

create test dataset

---

ngi_pipeline/database/classes.py
ngi_pipeline/engines/piper_ngi/launchers.py
ngi_pipeline/engines/piper_ngi/local_process_tracking.py
ngi_pipeline/engines/piper_ngi/parsers.py

Maybe it works... maybe it doesnt....

adding duplication rate parsing

---

ngi_pipeline/engines/piper_ngi/database.py
scripts/NGI_pipeline_test.py

Aka stuff I should probably bundle together with a big update but will probably forget before it happens.

Various quickfixes

---

ngi_pipeline/engines/piper_ngi/local_process_tracking.py

Instead of adding the mean autosomal coverage of each sample seqrun to get the total, it's now obtained from 06.
I plan to also add the reads parsing as well.

Adding sample coverage parsing from qualimap

---

ngi_pipeline/conductor/flowcell.py

Apparently, there is a document governing this, and we now have a case where this is needed...

following guidelines on project names

---

CONTRIBUTING.md
ngi_pipeline/__init__.py
setup.py

Hoping this will improve the usage of version numbering, as it's quite useful.

Added Contributing.md and moved version number

---

ngi_pipeline/conductor/flowcell.py

fix libprep variable

---

ngi_pipeline/conductor/flowcell.py

Fixing problem identified with pull request https://github.com/NationalGenomicsInfrastructure/ngi_pipeline/commit/27842335f70e386567bc351daa95b16a37ad91ff
Tested locally on Stockholm env.

fixing problem with path to missing DATA 

---

.travis.yml
ACKNOWLEDGEMENTS.txt
ngi_pipeline/__init__.py
requirements.txt

Added acknowledgements file
Added functional travis self test; this means some of the quickfixes for TravisCI of taca-ngi-pipeline can be removed.
Fixed the requirements so incompatiable ipython version isn't installed.

Travis & Acknowledgements

---

ngi_pipeline/__init__.py

This new version contains:
- samples are set to STALE upon organisation
- improved genotyping for stockholm
- static files for Stockholm Genotyping

version bump

---

ACKNOWLEDGEMENTS.txt
ACKNOWLEDGEMENTS_S.txt
ACKNOWLEDGEMENTS_U.txt

Updated acknowledgement text

---

ngi_pipeline/engines/piper_ngi/launchers.py

Phil edit: This should make the matching more specific, as it requires the sample name to be present in the filenames as well.

added sample name to md5 check

---

ngi_pipeline/engines/piper_ngi/launchers.py
ngi_pipeline/engines/rna_ngi/launchers.py
ngi_pipeline/tests/utils/test_filesystem.py
ngi_pipeline/utils/filesystem.py

Will skip index fastq files when launching the piper_ngi and rna_ngi pipelines

filter out index files from analyses

---

ngi_pipeline/engines/sarek/models.py

Renamed *singularity* to *container* in `irma_provision`. So fixing it here :)

small renaming

---

ngi_pipeline/conductor/classes.py
ngi_pipeline/engines/sarek/models.py
ngi_pipeline/tests/engines/sarek/test_launchers.py

This PR makes sure to exclude any fastq index files found when launching analysis

exclude index files from sarek analysis

---

ngi_pipeline/engines/sarek/local_process_tracking.py
ngi_pipeline/engines/sarek/models/sample.py
ngi_pipeline/engines/sarek/models/sarek.py
ngi_pipeline/engines/sarek/process.py
ngi_pipeline/tests/engines/sarek/models/test_sarek.py
ngi_pipeline/tests/engines/sarek/test_local_process_tracking.py
ngi_pipeline/tests/engines/sarek/test_process.py

This will make the pipeline remove nextflow's `work` directory after a successful analysis.

do cleanup of work directory after successful analysis

---

ngi_pipeline/engines/sarek/database.py
ngi_pipeline/engines/sarek/exceptions.py
ngi_pipeline/engines/sarek/models/sarek.py
ngi_pipeline/tests/engines/sarek/models/test_sarek.py
ngi_pipeline/tests/engines/sarek/test_launchers.py
test_ngi_config.yaml

Small update which makes better use of the Charon fields for "pipeline", "reference" and "best_practice_analysis" w.r.t. launching Sarek.

improve fetching of analysis pipeline and reference from charon

---

ngi_pipeline/utils/config.py

Added to stop the yaml.load warning message.

Added yaml loader type to stop display of warning message

---

ngi_pipeline/conductor/flowcell.py

Associated with validation 22_01_MiSeq Nori and Bombur upgrade to Win10

Special samplesheet path for MiSeq

---

ngi_pipeline/conductor/flowcell.py
ngi_pipeline/tests/conductor/test_flowcell.py
ngi_pipeline/tests/utils/test_parsers.py
requirements.txt

This reverts commit 98238a265d7790f844eafcd081f8380aff3611e7.

Revert "parse sample name from fastq file instead of sample directory"
