NationalGenomicsInfrastructure/ngi_pipeline

- ngi_pipeline/engines/piper_ngi/local_process_tracking.py
If piper_exit_code is "", the test >0 returns true, and the samples are marked as failed even though they didnt even start. yay me again.
> Everyone knows that "" > 0

- ngi_pipeline/engines/piper_ngi/local_process_tracking.py
allows to add extra args to the recurse_for_every_seqrun_in_sample call, which can be used to reset coverage or amount of reads when relaunching a sample
> meeting at half point

- ngi_pipeline/engines/qc_ngi/launchers.py
- ngi_pipeline/engines/qc_ngi/workflows.py
Checks for the existence of the output files and that they are newer (more recently modified) than the input fastq files
> Don't rerun QC analyses (FastQC, fastq_screen) if not needed

- ngi_pipeline/engines/piper_ngi/launchers.py
I'll add some file-checking to this but for now it's up to the user if they want to rerun analyses
> Genotype jobs rerun without forcing

- ngi_pipeline/engines/piper_ngi/local_process_tracking.py
Good spot by Pär Lundin, 
the field to update at seqrun level is not analysis_status but alignment_status, so recurse_sample_status should be called with the proper value.
This causes the seqrun not to be updated to DONE, which in turns causes the coverage update to fail. 
No charon errors were raised though, which is a bit unsettling.
> Fixing the wrong field being updated in Charon. 

- ngi_pipeline/engines/piper_ngi/launchers.py
Dumb. Now the `--keep-existing-files` flag will work.
> Bugfix: missing space in rsync command

- requirements.txt
- these requirements were in conflict with `ngi_reports`
> loosen up requirements for nose and python-dateutil

- ngi_pipeline/utils/parsers.py
a sample not having seqruns blocks organization
This will make it go all the libpreps before starting to complain.
> fixing case where the first libprep of 

- ngi_pipeline/conductor/flowcell.py
because some of them seem to have this kind of name instead of X_XXXXXXX_00_00
> handling projects of the form XX_XXXXX_00_00

- ngi_pipeline/server/handlers.py
- ngi_pipeline/server/main.py
For integration tests it would be great to have a end-point which one can issue requests to in the same way that one can issue requests to the real flowcell analysis end-point, but without actually starting anything.
> Added a test end-point to the ngi_pipline server

- nestor_ngi_config.yaml
- ngi_pipeline/utils/filesystem.py
Apparently, you can't use lmod like this on Irma. Therefore, moving the path to the configuration file allows any lmod to be used.
> moving lmod to the configuration file

- ngi_pipeline/engines/piper_ngi/database.py
- ngi_pipeline/utils/communication.py
Fixes for two small problems:
Uppmax was having some problems with invalid sender.
If the config pointed the database to a folder that didn't exist, ngi_pipeline refused to create the db. It would however create the db if the folder existed.
Changes or downright refusal is ok. Just play nice.
> Updated origin & let db create folders

- ngi_pipeline/conductor/flowcell.py
- ngi_pipeline/tests/utils/test_filesystem.py
- ngi_pipeline/utils/filesystem.py
- Uppsala projects would not be found as long as the Sthlm project_data_dir was a valid path. Changed so that all alternative locations are searched.
> fixed search for uppsala projects in locate_projects

- DELIVERY.README.txt
Since we do not recalibrate variants any more the file names are different.
> Removed *recalibrated* from DELIVERY.README.txt

- ngi_pipeline/engines/piper_ngi/local_process_tracking.py
- ngi_pipeline/utils/post_analysis.py
This adds a multiqc run at the end of any sample analysis. This assumes that "multiqc" can be called from within the environment used by the ngi_pipeline. 
If it fails, you'll get a log message, and that's about it. 
The analysis will be stored in a folder named "multiqc" alongside "piper_ngi" and "qc_ngi".
> adding multiqc as a post_process step

- ngi_pipeline/__init__.py
- ngi_pipeline/conductor/flowcell.py
- ngi_pipeline/engines/piper_ngi/command_creation_config.py
- ngi_pipeline/utils/communication.py
- Output is now written to `<base_root:>/<uppnexid_from_folder_struct>/<top_dir:>/` rather than the previous `/proj/<uppnexid_from_folder_struct>/<top_dir:>/`. Since `base_root` equals `/proj/` for the production installation anyway, this should cause no issues. It does however make running a staging or test version less "magical".
- NGI_Pipeline now correctly works with the UPPMAX's module installation of piper
> Updates to sort out irma compatibility

- scripts/bam2fastq.sh
@vezzi this way the read group information is preserved: tested on a smaller BAM file so far.
> Converting BAMs to FASTQ and preserving read group info

- ngi_pipeline/engines/piper_ngi/workflows.py
This PR adds the `--temp_directory` argument in calls to piper. This is in order to have piper write temporary files on the scratch area of the compute nodes rather than in the current working directory on the main filesystem.
@vezzi and @sylvinite, review is welcome
> pass temp_directory argument to piper

- ngi_pipeline/conductor/classes.py
Running `ngi_pipeline_start.py analyze project L.Dalen_17_02` was getting the following exception:
(Figured out, that this project was not supposed to be BP-ed (panthera project), but still fixing the typo to process exception correctly)
```
2017-02-24 11:08:09,411 - ngi_pipeline.utils.filesystem - INFO - Adding fastq file "P7402_2004_S4_L004_R1_001.fastq.gz" to seqrun "170216_ST-E00198_0202_AHGVLWALXX"
Traceback (most recent call last):
File "/lupus/ngi/production/v1.5/sw/anaconda/envs/NGI/bin/ngi_pipeline_start.py", line 313, in <module>
generate_bqsr_bam=args.generate_bqsr_bam)
File "/lupus/ngi/production/v1.5/sw/anaconda/envs/NGI/lib/python2.7/site-packages/ngi_pipeline/utils/classes.py", line 31, in __call__
return self.f(**kwargs)
File …
```
> conductor.classes: fixing uppercase name self.LOG

- ngi_pipeline/database/classes.py
- ngi_pipeline/database/filesystem.py
- ngi_pipeline/engines/piper_ngi/local_process_tracking.py
- scripts/gt_concordance.py
Until now a sample was transitioning from FRESH to STALE when starting BP, but then this affected the status of samples that do not undergo BP (non WHG).
I changed the logic in such  a way that now samples become STALE when we organise them.
In Stockholm case if new data is produced ACHERON will set the status of a STALE sample to FRESH again and upon organisation the sample will become again STALE. 
This is the first of three PR for GRUS-delivery
> FRESH --> STALE upon FC organisation

- ngi_pipeline/engines/qc_ngi/workflows.py
- ngi_pipeline/utils/parsers.py
I changed this PR since the original solution didn't work. The problem being that /ngi_pipeline/ngi_pipeline/utils/parsers.py was breaking before we even got to my fix. 
Thanks to the staging environment I was able to test and debug this. My new solution is simply to add the index files to the list of fastq files to analyse. I've tested this on project P7607 and it seems to work fine.
> Allow index file to be passed to QC step

- ngi_pipeline/conductor/flowcell.py
- ngi_pipeline/database/filesystem.py
- ngi_pipeline/database/local_process_tracking.py
- ngi_pipeline/engines/bcbio_ngi/__init__.py
- ngi_pipeline/engines/piper_ngi/command_creation_config.py
- ngi_pipeline/engines/piper_ngi/launchers.py
- ngi_pipeline/engines/piper_ngi/local_process_tracking.py
- ngi_pipeline/engines/piper_ngi/utils.py
- ngi_pipeline/engines/piper_ngi/workflows.py
- ngi_pipeline/engines/qc_ngi/launchers.py
- ngi_pipeline/engines/qc_ngi/workflows.py
- ngi_pipeline/utils/charon.py
- ngi_pipeline/utils/filesystem.py
- ngi_pipeline/utils/parsers.py
- scripts/ngi_pipeline_start.py
This PR changes all of occurrences of `LOG.warn` to `LOG.warning`. `warn` is not a function of `logging` and would therefore make the pipeline crash.
> LOG.warn -> LOG.warning

- ngi_pipeline/engines/sarek/local_process_tracking.py
a raised exception during local db to charon sync will not break the iteration
> continue updating charon status even if a sample raises exception

- ngi_pipeline/engines/sarek/models/workflow.py
- ngi_pipeline/engines/sarek/process.py
- ngi_pipeline/tests/utils/test_parsers.py
- ngi_pipeline/utils/parsers.py
This PR updates the path to the QualiMap result file which changed in Sarek 2.3. The default slurm time allocation for the cextflow control job was increased to 72h (could be needed for higher coverage samples). In addition, a fix to the logic matching the samplesheet rows to the fastq filename index, assigned by bcl2fastq was supplied.
> Fix path to bamqc results

- ngi_pipeline/tests/utils/test_parsers.py
- ngi_pipeline/utils/parsers.py
In Uppsala, we have the library prep information in the sample sheet and need to match the Fastq file to the sample sheet entry in order to retrieve it. This corrects the logic for doing that so that the sample id is the only field determining the sample number.
> remove barcode from sample number logic

- requirements.txt
Found this when Travis started failing for taca-ngi-pipeline which has a dependency on ngi-pipeline.
> Update req to keep supporting py2.7

- ngi_pipeline/conductor/flowcell.py
- ngi_pipeline/tests/conductor/test_flowcell.py
- ngi_pipeline/tests/utils/test_parsers.py
When organizing a flow cell, ngi_pipeline would deduce the sample_name from the name of the directory containing the fastq files (e.g. `FC/Unaligned/AB-1234/AB-1234-101`). For `bcl2fastq`, this corresponds to the `SampleID` field in the samplesheet, whereas the fastq file name prefix (up until the `_S1`) actually corresponds to the `SampleName` field in the samplesheet.
This meant that samples having multiple library preps sequenced in the same lane would not be organized together since they would have the same name but different sample ids. 
This PR changes so that ngi_pipeline deduces the sample_name from the fastq file prefix and the sample_id from the sample directory. This way, samples having different `SampleId`s but same `SampleName` in the samplesheet will be organized together.
> parse sample name from fastq file instead of sample directory

- ngi_pipeline/conductor/classes.py
- ngi_pipeline/conductor/launchers.py
- ngi_pipeline/database/classes.py
- ngi_pipeline/database/filesystem.py
- ngi_pipeline/engines/sarek/launchers.py
- ngi_pipeline/engines/sarek/local_process_tracking.py
- ngi_pipeline/engines/sarek/models/sample.py
- ngi_pipeline/engines/sarek/models/sarek.py
- ngi_pipeline/engines/sarek/models/workflow.py
- ngi_pipeline/engines/sarek/process.py
- ngi_pipeline/tests/database/test_filesystem.py
- ngi_pipeline/tests/engines/sarek/models/test_workflow.py
- ngi_pipeline/tests/engines/sarek/test_local_process_tracking.py
- ngi_pipeline/tests/fc_from_samplesheet.py
- requirements.txt
- scripts/ngi_pipeline_start.py
- scripts/update_charon_with_project_query.py
- test_ngi_config.yaml
This PR enables starting one Sarek process for an entire project rather than one process per sample (i.e. to do a `batch-analysis`).
- If passing the `--batch-analysis` argument to `ngi_pipeline_start.py` when launching the analysis for a project, all samples in the project will be started in the same nexflow process (default is to start one process per sample).
- Also, upon flow cell organization, the default `best_practice_analysis`, `pipeline` and `reference` set in Charon will be `wgs_germline`, `sarek` and `GRCh38`. These default values can be overridden on the command line.
- The sbatch stdout and stderr files will have the slurm job id in the filename instead of a timestamp.
> Batch sarek analyses

- ngi_pipeline/conductor/flowcell.py
The regular expression used to recognize projects from Uppsala is no longer compatible with our FU-projects. Because of this we can not use ngi-pipeline to organize data in NGI/DATA before starting analysis. This very minor update hopefully solves this issue.
> Changed re to recognize NGI-U FU-projects
